<a href="https://colab.research.google.com/github/O-Kpy/Machine-Learning-Lectures/blob/main/Machine_Learning_Andrew_Ng.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lecture 3 Linear Algebra Review

* 머신러닝을 위해 알아야할 Algebra

* 스칼라, 벡터, 행렬

* 스칼라, 벡터와 행렬의 연산

스칼라, 매트릭스 연산
```
import numpy as np
a = np.array([(3,2,1), (2,6,7)])
b = np.array([(1)])
a + b

>>array([[4, 3, 2],
         [3, 7, 8]])

a * b

>>array([[3, 2, 1],
         [2, 6, 7]])
```

벡터, 행렬 연산


```
import numpy as np
a = np.array([(3,2), (2,6), (7,5)])
b = np.array([(1),(2)])
a * b

>>array([[ 3,  4],
         [ 2, 12],
         [ 7, 10]])

a + b

>>array([[4, 4],
         [3, 8],
         [8, 7]])
```

matrix와 matrix연산의 설명은 생략한다.(m*n, n*m n과 n이 같으면 연산 가능)

* matrix연산에서 A * B와 B * A는 같지 않다.



